## Basic Configuration
baseurl = "https://cloud.italia.it"
languageCode = "it-it"

title = "Cloud della PA"
theme = "hugo-theme-bootstrap-italia"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30
#paginate = 5


## Site Settings
[Params]
  author = "AgID - Team Digitale"
  ente = "AgID - Team Digitale"
  siteTitle = "cloud.italia.it"
  siteDescription = "Il Cloud della PA"

#  footerColumn1Title = "Lorem Ipsum"
#  footerColumn1Text = "Lorem Ipsum"
#  footerColumn1Links = [
#    { label = "Link 1", url = "#" },
#    { label = "Link 2", url = "#" }
#  ]

#  footerColumn2Title = "Lorem Ipsum"
#  footerColumn2Text = "Lorem Ipsum"

  footerBottomLinks = [
    { label = "Note legali", url = "https://developers.italia.it/it/note-legali/" },
    { label = "Privacy policy", url = "https://developers.italia.it/it/privacy-policy/" }
  ]
