## Basic Configuration
baseurl = "https://cloud.italia.it"
languageCode = "it-it"

title = "Cloud della PA"
theme = "hugo-theme-bootstrap-italia"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30
#paginate = 5


## Site Settings
[Params]
  author = "AgID - Team Digitale"
  ente = "AgID - Team Digitale"
  siteTitle = "Il Cloud della PA"
  siteDescription = "Inserire qui la tag line"

#  footerColumn1Title = "Lorem Ipsum"
#  footerColumn1Text = "Lorem Ipsum"
#  footerColumn1Links = [
#    { label = "Link 1", url = "#" },
#    { label = "Link 2", url = "#" }
#  ]

#  footerColumn2Title = "Lorem Ipsum"
#  footerColumn2Text = "Lorem Ipsum"

#  footerBottomLinks = [
#    { label = "Note legali", url = "#" },
#    { label = "Privacy policy", url = "#" }
#  ]
