[[redirects]]
  from = "/marketplace/*"
  to = "https://156.54.185.159/marketplace/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/simplesaml/*"
  to = "https://156.54.185.159/simplesaml/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
