[[redirects]]
  from = "/marketplace"
  to = " https://156.54.185.159/marketplace"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/simplesaml"
  to = "https://156.54.185.159/simplesaml"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
