[[redirects]]
  from = "/marketplace/*"
  to = "https://156.54.185.159/marketplace/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/simplesaml/*"
  to = "https://156.54.185.159/simplesaml/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/projects/cloud-italia-docs/*"
  to = "https://cloud-italia.readthedocs.io/projects/cloud-italia-docs/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-RTD-SLUG = "cloud-italia-docs"

